version: 2
updates:
  # Monitor your npm (pnpm) dependencies
  - package-ecosystem: "npm"
    directory: "/" # Location of your package.json
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    commit-message:
      prefix: "⬆️ Update > "
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    open-pull-requests-limit: 1

  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "⬆️ Update > "
    labels:
      - "ci"
      - "automated"
